### ISSUE TITLE
[BUG] 관리자페이지 에세이 상세조회

### ISSUE THREAD

**Issue by daechan-jo** [team-echoist/server#327]
## **Describe the bug**
브라우저에서 관리자페이지의 에세이 상세조회 시 다음 에러가 발생중입니다.
![스크린샷 2024-08-03 오후 12 21 15](https://github.com/user-attachments/assets/259d0aea-4279-4725-872a-b38cb9b74285)

혹여나 서버가 응답객체를 직렬화하는 과정에서 `nickname` 프로퍼티가 누락되었는가 했지만 아니였고,
삭제(논리)된 유저의 경우 `nickname`이 null 이기 때문에 발생한건가 해서 다음과 같은 수정이 있었습니다. (참고: #324)

하지만 버그는 여전히 싱싱한 상태입니다.

<br />

## Device where issue occurred

- Device
- [x] Desktop
- [ ] Mobile

 - OS
- [ ] macOS
- [ ] Windows
- [ ] iOS
- [ ] AOS

 - Browser(options)

 - Version(options)

<br />

**Additional context**

**Comment by leeyounagh** [comment]
@jungyeon-rgb 정연사마 확인 부탁드리옵니다

**Comment by leeyounagh** [comment]
+ 문의하기 신규 업뎃이 안됨 ㅠㅠ

**Comment by leeyounagh** [comment]
![Image](https://github.com/user-attachments/assets/e7e5d23b-1cc2-4a6b-8564-1a6c5545716a)

에세이 완료

**Comment by daechan-jo** [comment]
문의목록 조회 내림차순으로 변경 완.

**Comment by daechan-jo** [comment]
# 에세이 상세조회 > 작성자조회시 이슈 발견

```json
{
    "success": false,
    "timestamp": "2024-08-05T01:07:45.272Z",
    "path": "/api/admin/users/undefined",
    "error": {
        "message": "Validation failed (numeric string is expected)",
        "error": "Bad Request"
    },
    "statusCode": 400
}
```

경로중 경로파라미터에 `undefined` 로 요청하고 있음.

**Comment by leeyounagh** [comment]
![Image](https://github.com/user-attachments/assets/e4ef4675-2c53-4f75-8982-c934ac2c9b92)

완료

**Comment by daechan-jo** [comment]
이슈 닫겠습니다 ㅋㅋ
