### ISSUE TITLE
[BUG] 관리자페이지 릴리즈노트

### ISSUE THREAD

**Issue by daechan-jo** [team-echoist/server#372]
## **Describe the bug**
- 릴리즈노트 삭제기능 없음
- 수정기능만 있는데, 수정시 새로운 객체가 생성됨
- 새로운 객체와 원본객체가 겹쳐서?보임

<br />

## **Screenshots**
![스크린샷 2024-08-14 오전 1 19 54](https://github.com/user-attachments/assets/aa98d498-5e5f-4d8d-864f-c14c7a42d62a)
![스크린샷 2024-08-14 오전 1 16 59](https://github.com/user-attachments/assets/b25bc9f7-33ef-4ec5-9fc1-00a33deeb728)

<br />

## Device where issue occurred

- Device
- [x] Desktop
- [ ] Mobile

 - OS
- [ ] macOS
- [ ] Windows
- [ ] iOS
- [ ] AOS

 - Browser(options)

 - Version(options)

<br />

**Additional context**

**Comment by daechan-jo** [comment]
변경하는김에 경로도 release로 바꿀게영 ㅎㅎ..

**Comment by leeyounagh** [comment]
까먹고 삭제기능 안넣었던것 같기도...
언능 해서 올려놓겠사옵니다 ㅋㅋㅋㅋ

**Comment by daechan-jo** [comment]
삭제api가 아예 없었어요 ㅋㅋㅋㅋ 수정api에도 버그가 있었고.. 수정하고 만들어놨습니다 ㅋㅋ

**Comment by leeyounagh** [comment]
![Image](https://github.com/user-attachments/assets/e7debf0e-b1fd-4268-9397-029e0a841d71)


아직 404 not found나오는데 원인을 모르겠습니당 ㅠㅠ

**Comment by daechan-jo** [comment]
늦게봤네요. 쿼리매개변수가 아니라 경로매개변수로 릴리즈 식별자를 넣어주세요

**Comment by leeyounagh** [comment]
![Image](https://github.com/user-attachments/assets/a5838632-a969-473d-bf14-b0d7c43fc86b)

---완료 했습니다 ---
